### PR TITLE
Added Protocol for 24 well plate dilution

### PR DESCRIPTION
**Pull request by abradle**
I intend to submit a series of chemistry protocols over next week or so. This is a starter - to see if it works with your way of working.

### CODE REVIEW

**Comment by abradle** [comment]
How do I add my own container formats to this? (I have them in JSON on my side).

**Comment by abradle** [comment]
Still struggling to add my own custom protocols - is that supported yet? No worries if not - but this seems a really cool feature!

**Comment by IanLondon** [comment]
Hey @abradle - this protocol looks great! Thank you for contributing. Unfortunately we don't support custom .json containers in Protocol Library right now, but if your container is a grid, you can use the `containers.create` function at the beginning of the protocol as in https://github.com/Opentrons/Protocols/blob/7a5ec71fbd876e662843f108fec57dc2959d454f/protocols/cell_culture_wash/cell_culture_wash.py#L5

**Comment by abradle** [comment]
@IanLondon ok - so I've finally got this to work. Would you like me to rebase? Or is it good to go now?

Best wishes,

Anthony

**Comment by IanLondon** [comment]
@abradle awesome, looks good! One request: could you please add back in the files (protocol + README) from `protocols/384_plate_filling/`? It looks like they are being deleted in your PR. 

Thank you!

**Comment by IanLondon** [comment]
@abradle looks like there's a small linting error: needs a blank line at the end of the file

`./protocols/384_plate_filling/384_plate_filling.py:28:1: W391 blank line at end of file` 

https://travis-ci.org/Opentrons/Protocols/builds/354303251#L544

**Pull request merged**
