### PR TITLE
3fb582

### PR DESCRIPTION
**Pull request by Koeng101**
Two things to be fixed - 

1. Need proper category
2. Need link for input CSV (shared over slack)

A quick note: On some of the for loops, there are short variables (ss for source_slot and ts for target_slot) because flake8 demanded that I make the lines shorter and I couldn't break up the for loop.

### CODE REVIEW

**Comment by Koeng101** [comment]
@chazmanc Could I get proper category for this?

**Comment by chazmanc** [comment]
@Koeng101 the category would be `PCR` --> `PCR Prep`

**Comment by Koeng101** [comment]
Just need the CSV file with a link now

**Comment by chazmanc** [comment]
I just made a template CSV in google docs based on your commented CSV structure. [Here is the link](https://docs.google.com/spreadsheets/d/15ddYgLTeaY4jjYTro1_AiAuMxNe6WrNxDndm7DE7Kgc/edit?usp=sharing)

**Pull request merged**
